version: 2

defaults: &defaults
  docker:
    - image: circleci/python:3.7.2
  working_directory: ~/project

jobs:
  test_mouse_recorder:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Install and Run
          command: |
            chmod +x scripts/execute/run.sh
            ./scripts/development/tools/run.sh --package mouse_recorder --username=circleci --max_iterations=5 --point_per_file=10 --sleep_time=0.1

workflows:
  version: 2
  test-all:
    jobs:
      - test_mouse_recorder


